datasource:
  matrix:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://175.102.16.11:3306/mr_money?useUnicode=true&characterEncoding=UTF-8
    username: mr_money_f
    password: uRaBH4qrmQvwiMVb6NlM

  msggw:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://175.102.16.11:3307/msggw?useUnicode=true&characterEncoding=UTF-8
    username: db_yanlian
    password: BMg7GFzUO4Iaq9CAhDkL

  local:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://jrdsn3d3c6w5883.mysql.rds.aliyuncs.com
    username: demoadmin
    password: demo_admin


taskExecutor:
  test:
    corePoolSize: 5
    keepAliveSeconds: 60
    maxPoolSize: 30
    queueCapacity: 1000
    rejectedExecutionHandler: CallerRunsPolicy
    threadNamePrefix: testExecutor-

server:
  port: 8099